const path = require('path');
const fs = require('node:fs');

module.exports = (env) => {
	const environment = env.production ? 'production' : 'development';

	let seed = undefined;
	if (environment === 'development') {
		seed = 977112;
	}

	const EnvironmentString = `/* THIS IS AN AUTOGENERATED FILE--DO NOT EDIT*/
const ENV = {
	environment: "${environment}",
	${seed && `seed: ${seed},`}
};

ENV.isDev = () => ENV.environment === 'development';

export default ENV;
`;

	try {
		fs.writeFileSync(path.resolve(__dirname, 'src', 'constants', 'env.js'), EnvironmentString);
	} catch (err) {
		console.log(err);
		process.exit(1);
	}

	return {
		entry: './src/index.js',
		output: {
			path: path.resolve(__dirname, 'dist'),
			filename: 'bundle.js',
		},
		mode: environment,
	};
};
